-- SQL Script to setup Supabase tables for the Bookstore app

-- 1. Create Products table
CREATE TABLE products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    author TEXT,
    publisher TEXT,
    year INTEGER,
    original_price NUMERIC,
    discount INTEGER DEFAULT 0,
    price NUMERIC,
    quantity INTEGER DEFAULT 0,
    image TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Product Categories junction table
CREATE TABLE product_categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    category_slug TEXT NOT NULL,
    UNIQUE(product_id, category_slug)
);

-- 3. Create Users table (Optional if using Supabase Auth, but kept for compatibility)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Orders table
CREATE TABLE orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    customer_address TEXT,
    items JSONB,
    total_amount NUMERIC,
    status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security (RLS) - Note: In a production app, you should set specific policies
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Simple public read access for demo purposes
CREATE POLICY "Public Read Access" ON products FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON product_categories FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON orders FOR SELECT USING (true);

-- Allow all for demo (WARNING: Not for production)
CREATE POLICY "Enable all for all" ON products FOR ALL USING (true);
CREATE POLICY "Enable all for all" ON product_categories FOR ALL USING (true);
CREATE POLICY "Enable all for all" ON users FOR ALL USING (true);
CREATE POLICY "Enable all for all" ON orders FOR ALL USING (true);

-- Insert initial admin user
INSERT INTO users (username, password, role, full_name)
VALUES ('admin', 'admin123', 'admin', 'Administrator');
